import { BACKEND_PATHS, BACKEND_PATHS_MAP } from '@/constants/backend-path'

export const BACKEND_NAVBAR_ITEMS: {
  link: string
  name: string
}[] = [
  { link: BACKEND_PATHS.BACKEND_HOME, name: BACKEND_PATHS_MAP[BACKEND_PATHS.BACKEND_HOME] },
  { link: BACKEND_PATHS.BACKEND_TAG, name: BACKEND_PATHS_MAP[BACKEND_PATHS.BACKEND_TAG] },
  { link: BACKEND_PATHS.BACKEND_NOTE, name: BACKEND_PATHS_MAP[BACKEND_PATHS.BACKEND_NOTE] }
]
